---
title: "PS270 Final Project"
author: "Sophia Phair"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to voting behavior and election analysis. Specifically, I'd like to look at voter turnout and how it is influenced by a certain factor, such as demographics, voting laws, geography, access, etc. I would do this by observing trends over multiple elections based on the factor(s) that I choose. 

## Research Question and Data

I will examine the following research question: In Wisconsin counties, does a higher proportion of absentee voting lead to increased voter turnout, controlling for socioeconomic and demographic characteristics? I will use county-level data from the Wisconsin Elections Commission combined with demographic and socioeconomic data from the U.S. Census. I hypothesize that counties where more people vote absentee will have higher turnout rates. The theoretical logic to support this claim is that absentee voting reduces the participation costs of voting, such as time, transportation, work schedules, etc., which would increase turnout rates across Wisconsin counties. The independent variable is the share of total votes cast by absentee ballot in a Wisconsin county (absentee voting rate). This would be measured as absentee ballots cast divided by total ballots cast in each Wisconsin county in a given election year. The dependent variable is the proportion of eligible voters in a Wisconsin county who voted (turnout rate), which would be measured as total ballots cast divided by the voting-age population. The variables to control for include percent college educated, percent age 65+, percent nonwhite, percent urban population, median household income, and possible partisan lean. These factors would all be analyzed at county level to account for confounding bias among different counties. Support for my hypothesis would be demonstrated through a positive correlation between absentee voting proportion and turnout, and my hypothesis would be disproved if the relationship between these variables is negative after controlling for potential confounders. 
